apiVersion: v2
appVersion: 1.7.1
description: A Helm chart deploying a worker pod that runs Bluesky plans
home: https://github.com/DiamondLightSource/blueapi
name: blueapi
type: application
version: 1.7.1
